### PR TITLE
All user management functionality

### PR DESCRIPTION
**Pull request by seant1**
* User Management jsp (list of all users, searchable by name and phone)
* Create customer
* Create staff (dropdown lists to validate manager email and contract type)
* Update customer/staff (all values including dropdowns populated with selected user details on edit page)
* Delete customer/staff
* Creating/updating/deleting redirects to User Management with confirmation/error message
* User Management button only shown to sysadmin (admin@iotbay.com)
* Remain logged in as sysadmin after creating/editing another user
* Show/redirect from deactivate/activate button depending on context (sysadmin, de/activated)

TODO:
* decide on css and make consistent
* some suggested validation change so sample data works (James 👀) - phone can start with not 0, state/city can be multiple words (e.g. San Francisco)

### CODE REVIEW

**Review by kevinleung56 — APPROVED** [review]
Looks good @seant1  :)

**Comment by seant1** [comment]
WOWW. validation from the dev master himself. what an honour!

**Comment by kevinleung56** [comment]
Oh actually I want to ask - you know how for edit -> activate/deactivate there's a pop-up prompt confirming their action - do you think that's fine for George or you reckon he'll give us 0?

**Comment by seant1** [comment]
I mean I like it but yeah.. maybe it's not worth keeping it in. doesn't hurt too much to take it out anyway

**Pull request merged**
